const R=document.getElementById('forge3d');
const left=R.querySelector('#f-left'),right=R.querySelector('#f-right'),status=R.querySelector('#f-status'),view=R.querySelector('#f-view'),overlay=R.querySelector('#f-overlay');
let THREE,OrbitControls,TransformControls,mergeVertices;
let scene,camera,renderer,orbit,gizmo,gizmoHelper,mesh,faceMark,brushCursor;
let workspace='object',gizmoMode='translate',space='world',wire=false,selectedFace=-1,nodeSelected='transform';
let baseGeometry=null,history=[],hist=-1,idN=1,strokeDirty=false,sculpting=false,lastPointer=null,lastBrushPoint=null,adjacency=null;
let brush={type:'Draw',radius:.65,strength:.18,falloff:'Smooth',symX:false,symY:false,symZ:false,spacing:.12};
let presets=[{name:'Clay Soft',type:'Clay',radius:.8,strength:.12,falloff:'Smooth',symX:false,symY:false,symZ:false,spacing:.12},{name:'Crease Fine',type:'Crease',radius:.32,strength:.14,falloff:'Sharp',symX:false,symY:false,symZ:false,spacing:.08}];
const nodes=[
 {id:'source',type:'source',enabled:true,p:{shape:'Box',custom:false,sizeX:2,sizeY:2,sizeZ:2,radius:1.25,height:2.5,segments:28}},
 {id:'transform',type:'transform',enabled:true,p:{px:0,py:1,pz:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1}},
 {id:'material',type:'material',enabled:true,p:{color:'#b9c9dc',roughness:.38,metalness:.06}},
 {id:'output',type:'output',enabled:true,p:{}}
];
const deformation=new Set(['twist','bend','taper','noise','spherize','flatten']);
const D={twist:{amount:90,axis:'y'},bend:{amount:45,axis:'x'},taper:{factor:.45,axis:'y'},noise:{strength:.18,frequency:2.2,seed:1},spherize:{factor:.5},flatten:{axis:'y',amount:0}};
const cloneNodes=()=>JSON.parse(JSON.stringify(nodes));
function snapGeom(g){return{p:Array.from(g.attributes.position.array),i:g.index?Array.from(g.index.array):null}}
function fromSnap(s){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(s.p,3));if(s.i)g.setIndex(s.i);g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function snapshot(){return{g:snapGeom(baseGeometry),n:cloneNodes()}}
function pushHistory(){if(!baseGeometry)return;history=history.slice(0,hist+1);history.push(snapshot());if(history.length>24)history.shift();hist=history.length-1;undoState()}
function undoState(){R.querySelector('#f-undo').disabled=hist<=0;R.querySelector('#f-redo').disabled=hist>=history.length-1}
function restore(idx){if(idx<0||idx>=history.length)return;hist=idx;baseGeometry?.dispose();baseGeometry=fromSnap(history[idx].g);nodes.splice(0,nodes.length,...JSON.parse(JSON.stringify(history[idx].n)));selectedFace=-1;evaluate();renderWorkspace();undoState()}
function sourceNode(){return nodes.find(n=>n.type==='source')}function transformNode(){return nodes.find(n=>n.type==='transform')}function materialNode(){return nodes.find(n=>n.type==='material')}
function makeSource(shape){const s=sourceNode().p;s.shape=shape;s.custom=false;let g;if(shape==='Sphere')g=new THREE.SphereGeometry(s.radius,Math.max(8,s.segments),Math.max(6,Math.round(s.segments*.65)));else if(shape==='Cylinder')g=new THREE.CylinderGeometry(s.radius,s.radius,s.height,Math.max(6,s.segments),Math.max(2,Math.round(s.segments/4)));else if(shape==='Torus')g=new THREE.TorusGeometry(s.radius,.4,Math.max(8,Math.round(s.segments/2)),Math.max(12,s.segments*2));else g=new THREE.BoxGeometry(s.sizeX,s.sizeY,s.sizeZ,Math.max(1,Math.round(s.segments/5)),Math.max(1,Math.round(s.segments/5)),Math.max(1,Math.round(s.segments/5)));baseGeometry?.dispose();baseGeometry=mergeVertices(g.toNonIndexed(),1e-5);g.dispose();baseGeometry.computeVertexNormals();selectedFace=-1;evaluate();pushHistory();renderWorkspace()}
function bounds(g){g.computeBoundingBox();const b=g.boundingBox;return{min:b.min.clone(),max:b.max.clone(),size:new THREE.Vector3().subVectors(b.max,b.min),center:new THREE.Vector3().addVectors(b.min,b.max).multiplyScalar(.5)}}
function av(v,a){return a==='x'?v.x:a==='y'?v.y:v.z}function sv(v,a,x){if(a==='x')v.x=x;else if(a==='y')v.y=x;else v.z=x}
function deform(g,n){const pos=g.attributes.position,p=n.p,b=bounds(g),v=new THREE.Vector3();g.computeVertexNormals();const nor=g.attributes.normal;for(let i=0;i<pos.count;i++){v.fromBufferAttribute(pos,i);if(n.type==='twist'){const h=Math.max(.0001,av(b.size,p.axis)),t=(av(v,p.axis)-av(b.min,p.axis))/h-.5,a=THREE.MathUtils.degToRad(p.amount)*t,c=Math.cos(a),s=Math.sin(a);if(p.axis==='y'){const x=v.x,z=v.z;v.x=x*c-z*s;v.z=x*s+z*c}else if(p.axis==='x'){const y=v.y,z=v.z;v.y=y*c-z*s;v.z=y*s+z*c}else{const x=v.x,y=v.y;v.x=x*c-y*s;v.y=x*s+y*c}}else if(n.type==='bend'){const h=Math.max(.0001,av(b.size,p.axis)),k=THREE.MathUtils.degToRad(p.amount)/h;if(Math.abs(k)>.000001){if(p.axis==='x'){const q=v.x-b.center.x,r=1/k+v.y;v.x=Math.sin(k*q)*r+b.center.x;v.y=Math.cos(k*q)*r-1/k}else if(p.axis==='y'){const q=v.y-b.center.y,r=1/k+v.z;v.y=Math.sin(k*q)*r+b.center.y;v.z=Math.cos(k*q)*r-1/k}else{const q=v.z-b.center.z,r=1/k+v.x;v.z=Math.sin(k*q)*r+b.center.z;v.x=Math.cos(k*q)*r-1/k}}}else if(n.type==='taper'){const h=Math.max(.0001,av(b.size,p.axis)),t=(av(v,p.axis)-av(b.min,p.axis))/h-.5,f=Math.max(.02,1+p.factor*t);if(p.axis==='y'){v.x*=f;v.z*=f}else if(p.axis==='x'){v.y*=f;v.z*=f}else{v.x*=f;v.y*=f}}else if(n.type==='noise'){const q=Math.sin((v.x+p.seed*.13)*p.frequency)*Math.cos((v.y+p.seed*.27)*p.frequency)*Math.sin((v.z+p.seed*.41)*p.frequency);v.x+=nor.getX(i)*q*p.strength;v.y+=nor.getY(i)*q*p.strength;v.z+=nor.getZ(i)*q*p.strength}else if(n.type==='spherize'){const r=(b.size.x+b.size.y+b.size.z)/6,t=v.clone().sub(b.center);if(t.lengthSq()>.000001)t.normalize().multiplyScalar(r).add(b.center);v.lerp(t,p.factor)}else if(n.type==='flatten')sv(v,p.axis,THREE.MathUtils.lerp(av(v,p.axis),p.amount,.8));pos.setXYZ(i,v.x,v.y,v.z)}pos.needsUpdate=true;g.computeVertexNormals();g.computeBoundingSphere();return g}
function evaluate(){if(!baseGeometry||!THREE)return;let g=baseGeometry.clone();for(const n of nodes)if(n.enabled&&deformation.has(n.type))g=deform(g,n);if(!mesh){mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial());mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh)}else{mesh.geometry.dispose();mesh.geometry=g}const m=materialNode().p;mesh.material.color.set(m.color);mesh.material.roughness=m.roughness;mesh.material.metalness=m.metalness;mesh.material.wireframe=wire;const t=transformNode().p;mesh.position.set(t.px,t.py,t.pz);mesh.rotation.set(THREE.MathUtils.degToRad(t.rx),THREE.MathUtils.degToRad(t.ry),THREE.MathUtils.degToRad(t.rz));mesh.scale.set(t.sx,t.sy,t.sz);gizmo?.attach(mesh);updateFaceMark();updateStatus()}
function bakeModifiers(){const mods=nodes.filter(n=>deformation.has(n.type));if(!mods.length)return;baseGeometry.dispose();baseGeometry=mesh.geometry.clone();for(let i=nodes.length-1;i>=0;i--)if(deformation.has(nodes[i].type))nodes.splice(i,1);sourceNode().p.custom=true;sourceNode().p.shape='Custom';evaluate();pushHistory()}
function updateStatus(){const v=baseGeometry?.attributes.position.count||0,f=baseGeometry?.index?baseGeometry.index.count/3:v/3;status.textContent=`${workspace[0].toUpperCase()+workspace.slice(1)} mode · ${Math.round(v).toLocaleString()} vertices · ${Math.round(f).toLocaleString()} triangles · ${nodes.filter(n=>deformation.has(n.type)&&n.enabled).length} live modifier nodes`}
function setWorkspace(w){workspace=w;R.querySelectorAll('[data-work]').forEach(b=>b.classList.toggle('active',b.dataset.work===w));selectedFace=-1;sculpting=false;orbit.enabled=true;brushCursor.visible=false;gizmo.visible=w==='object'||w==='nodes';gizmo.enabled=gizmo.visible;overlay.textContent=w==='sculpt'?'Sculpt: drag directly on mesh · orbit using empty space · symmetry works in object-local axes':w==='edit'?'Edit: tap a triangle face to select it · use manual mesh operations at left':'Orbit: one finger / mouse drag · Zoom/pan: two fingers';renderWorkspace();updateStatus()}
function btns(items){return`<div class="f-tools">${items.map(([id,label])=>`<button type="button" class="f-tool" data-tool="${id}">${label}</button>`).join('')}</div>`}
function num(label,key,val,min,max,step=.1){return`<div class="f-field"><label>${label}</label><input type="number" data-val="${key}" value="${val}" min="${min}" max="${max}" step="${step}" inputmode="decimal"></div>`}
function range(label,key,val,min,max,step=.01){return`<div class="f-field"><label>${label}</label><div class="f-range-row"><input type="range" data-range="${key}" value="${val}" min="${min}" max="${max}" step="${step}"><input type="number" data-val="${key}" value="${val}" min="${min}" max="${max}" step="${step}"></div></div>`}
function bindValues(obj,callback){R.querySelectorAll('[data-val]').forEach(el=>el.addEventListener('change',()=>{let v=Number(el.value);if(!Number.isFinite(v))return;const min=Number(el.min),max=Number(el.max);if(Number.isFinite(min))v=Math.max(min,v);if(Number.isFinite(max))v=Math.min(max,v);el.value=String(v);obj[el.dataset.val]=v;callback?.()}));R.querySelectorAll('[data-range]').forEach(el=>el.addEventListener('input',()=>{const v=Number(el.value);obj[el.dataset.range]=v;const n=R.querySelector(`[data-val="${el.dataset.range}"]`);if(n)n.value=String(v);callback?.(false)}))}
function renderWorkspace(){R.querySelector('#f-left-title').textContent=workspace==='object'?'Object Tools':workspace==='edit'?'Manual Modeling':workspace==='sculpt'?'Sculpt Brushes':'Node Stack';R.querySelector('#f-right-title').textContent=workspace==='object'?'Object Properties':workspace==='edit'?'Mesh Operations':workspace==='sculpt'?'Brush Properties':'Node Inspector';if(workspace==='object')renderObject();else if(workspace==='edit')renderEdit();else if(workspace==='sculpt')renderSculpt();else renderNodes()}
function renderObject(){left.innerHTML=`<div class="f-label">Primitive</div>${btns([['Box','Box'],['Sphere','Sphere'],['Cylinder','Cylinder'],['Torus','Torus']])}<div class="f-divider"></div><div class="f-label">Object</div>${btns([['ResetTransform','Reset Transform'],['CenterOrigin','Center Geometry']])}`;const t=transformNode().p,m=materialNode().p;right.innerHTML=`<div class="f-label">Position</div><div class="f-grid3">${num('X','px',t.px,-100,100)}${num('Y','py',t.py,-100,100)}${num('Z','pz',t.pz,-100,100)}</div><div class="f-label">Rotation °</div><div class="f-grid3">${num('X','rx',t.rx,-3600,3600,1)}${num('Y','ry',t.ry,-3600,3600,1)}${num('Z','rz',t.rz,-3600,3600,1)}</div><div class="f-label">Scale</div><div class="f-grid3">${num('X','sx',t.sx,.01,100)}${num('Y','sy',t.sy,.01,100)}${num('Z','sz',t.sz,.01,100)}</div><div class="f-divider"></div><div class="f-field"><label>Material Color</label><input class="f-color" id="f-color" type="color" value="${m.color}"></div>${range('Roughness','roughness',m.roughness,0,1)}${range('Metalness','metalness',m.metalness,0,1)}`;left.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{const x=b.dataset.tool;if(['Box','Sphere','Cylinder','Torus'].includes(x))makeSource(x);else if(x==='ResetTransform'){Object.assign(t,{px:0,py:1,pz:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1});evaluate();pushHistory();renderObject()}else if(x==='CenterOrigin'){bakeModifiers();baseGeometry.computeBoundingBox();const c=baseGeometry.boundingBox.getCenter(new THREE.Vector3());baseGeometry.translate(-c.x,-c.y,-c.z);evaluate();pushHistory()}}));bindValues(t,()=>{evaluate();pushHistory()});const color=right.querySelector('#f-color');color.addEventListener('input',()=>{m.color=color.value;evaluate()});color.addEventListener('change',pushHistory)}
function renderEdit(){left.innerHTML=`<div class="f-label">Selected Face</div>${btns([['Extrude','Extrude'],['Inset','Inset'],['Bevel','Bevel'],['DeleteFace','Delete Face'],['FlipFace','Flip Normal']])}<div class="f-divider"></div><div class="f-label">Whole Mesh</div>${btns([['Subdivide','Subdivide'],['Smooth','Smooth'],['Weld','Weld'],['MirrorX','Mirror X'],['Recalc','Recalc Normals'],['Bake','Bake Nodes']])}`;right.innerHTML=`<div class="f-help">Tap a visible triangle in the viewport. Extrude, inset and bevel operate on that selected face. Whole-mesh tools modify the base topology directly.</div><div class="f-divider"></div>${num('Extrude Distance','extrude',.35,-10,10,.05)}${num('Inset Amount','inset',.18,.01,.9,.01)}${num('Bevel Amount','bevel',.12,-3,3,.01)}${num('Smooth Strength','smooth',.35,0,1,.05)}${num('Weld Tolerance','weld',.0001,.000001,.1,.0001)}<div class="f-msg" id="f-editmsg">${selectedFace>=0?'Face '+selectedFace+' selected.':'No face selected.'}</div>`;const vals={extrude:.35,inset:.18,bevel:.12,smooth:.35,weld:.0001};right.querySelectorAll('[data-val]').forEach(el=>{vals[el.dataset.val]=Number(el.value);el.addEventListener('change',()=>vals[el.dataset.val]=Number(el.value))});left.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>editTool(b.dataset.tool,vals)))}
function indicesOf(g){if(g.index)return Array.from(g.index.array);return Array.from({length:g.attributes.position.count},(_,i)=>i)}
function faceIndices(g,fi){const idx=indicesOf(g),o=fi*3;if(o+2>=idx.length)return null;return[idx[o],idx[o+1],idx[o+2]]}
function editTool(tool,v){if(tool==='Bake'){bakeModifiers();renderWorkspace();return}bakeModifiers();if(['Extrude','Inset','Bevel','DeleteFace','FlipFace'].includes(tool)&&selectedFace<0){right.querySelector('#f-editmsg').textContent='Select a face first.';return}if(tool==='Subdivide')subdivide();else if(tool==='Smooth')smoothAll(v.smooth);else if(tool==='Weld')weld(v.weld);else if(tool==='MirrorX')mirrorX();else if(tool==='Recalc'){baseGeometry.computeVertexNormals()}else faceOperation(tool,v);sourceNode().p.custom=true;sourceNode().p.shape='Custom';selectedFace=-1;evaluate();pushHistory();renderWorkspace()}
function faceOperation(tool,v){const g=baseGeometry,idx=indicesOf(g),f=faceIndices(g,selectedFace);if(!f)return;const pos=Array.from(g.attributes.position.array),A=new THREE.Vector3().fromArray(pos,f[0]*3),B=new THREE.Vector3().fromArray(pos,f[1]*3),C=new THREE.Vector3().fromArray(pos,f[2]*3),center=A.clone().add(B).add(C).multiplyScalar(1/3),normal=B.clone().sub(A).cross(C.clone().sub(A)).normalize();if(tool==='DeleteFace'){idx.splice(selectedFace*3,3)}else if(tool==='FlipFace'){const o=selectedFace*3;[idx[o+1],idx[o+2]]=[idx[o+2],idx[o+1]]}else{idx.splice(selectedFace*3,3);let a=A.clone(),b=B.clone(),c=C.clone();if(tool==='Extrude'){a.addScaledVector(normal,v.extrude);b.addScaledVector(normal,v.extrude);c.addScaledVector(normal,v.extrude)}else{const amount=tool==='Inset'?v.inset:Math.min(.9,Math.abs(v.bevel)*.7+.08);a.lerp(center,amount);b.lerp(center,amount);c.lerp(center,amount);if(tool==='Bevel'){a.addScaledVector(normal,v.bevel);b.addScaledVector(normal,v.bevel);c.addScaledVector(normal,v.bevel)}}const n0=pos.length/3;pos.push(a.x,a.y,a.z,b.x,b.y,b.z,c.x,c.y,c.z);idx.push(n0,n0+1,n0+2,f[0],f[1],n0+1,f[0],n0+1,n0,f[1],f[2],n0+2,f[1],n0+2,n0+1,f[2],f[0],n0,f[2],n0,n0+2)}const ng=new THREE.BufferGeometry();ng.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));ng.setIndex(idx);ng.computeVertexNormals();baseGeometry.dispose();baseGeometry=ng}
function subdivide(){const g=baseGeometry,pos=Array.from(g.attributes.position.array),idx=indicesOf(g);if(idx.length/3>40000){alertMsg('Subdivision limit reached for mobile performance.');return}const edge=new Map(),mid=(a,b)=>{const lo=Math.min(a,b),hi=Math.max(a,b),k=lo+'_'+hi;if(edge.has(k))return edge.get(k);const i=pos.length/3;pos.push((pos[a*3]+pos[b*3])/2,(pos[a*3+1]+pos[b*3+1])/2,(pos[a*3+2]+pos[b*3+2])/2);edge.set(k,i);return i},out=[];for(let i=0;i<idx.length;i+=3){const a=idx[i],b=idx[i+1],c=idx[i+2],ab=mid(a,b),bc=mid(b,c),ca=mid(c,a);out.push(a,ab,ca,ab,b,bc,ca,bc,c,ab,bc,ca)}const ng=new THREE.BufferGeometry();ng.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));ng.setIndex(out);ng.computeVertexNormals();baseGeometry.dispose();baseGeometry=ng}
function adjacencyFor(g){const n=g.attributes.position.count,a=Array.from({length:n},()=>new Set()),idx=indicesOf(g);for(let i=0;i<idx.length;i+=3){const x=idx[i],y=idx[i+1],z=idx[i+2];a[x].add(y);a[x].add(z);a[y].add(x);a[y].add(z);a[z].add(x);a[z].add(y)}return a}
function smoothAll(s=.35){const p=baseGeometry.attributes.position,a=adjacencyFor(baseGeometry),old=Array.from(p.array);for(let i=0;i<p.count;i++){if(!a[i].size)continue;let x=0,y=0,z=0;for(const j of a[i]){x+=old[j*3];y+=old[j*3+1];z+=old[j*3+2]}const d=a[i].size;p.setXYZ(i,THREE.MathUtils.lerp(old[i*3],x/d,s),THREE.MathUtils.lerp(old[i*3+1],y/d,s),THREE.MathUtils.lerp(old[i*3+2],z/d,s))}p.needsUpdate=true;baseGeometry.computeVertexNormals()}
function weld(t){const n=mergeVertices(baseGeometry.toNonIndexed(),Math.max(1e-7,t));baseGeometry.dispose();baseGeometry=n;baseGeometry.computeVertexNormals()}
function mirrorX(){const p=Array.from(baseGeometry.attributes.position.array),idx=indicesOf(baseGeometry),n=p.length/3,mp=[];for(let i=0;i<n;i++)mp.push(-p[i*3],p[i*3+1],p[i*3+2]);const mi=[];for(let i=0;i<idx.length;i+=3)mi.push(idx[i]+n,idx[i+2]+n,idx[i+1]+n);const ng=new THREE.BufferGeometry();ng.setAttribute('position',new THREE.Float32BufferAttribute(p.concat(mp),3));ng.setIndex(idx.concat(mi));ng.computeVertexNormals();baseGeometry.dispose();baseGeometry=ng}
function alertMsg(t){status.textContent=t}
function renderSculpt(){const brushes=['Draw','Clay','Inflate','Smooth','Flatten','Pinch','Crease','Grab','Scrape'];left.innerHTML=`<div class="f-label">Brush</div><div class="f-tools">${brushes.map(x=>`<button type="button" class="f-tool ${brush.type===x?'active':''}" data-brush="${x}">${x}</button>`).join('')}</div><div class="f-divider"></div><div class="f-label">Custom Presets</div><div class="f-presets" id="f-presets"></div>`;right.innerHTML=`${range('Radius','radius',brush.radius,.05,5,.01)}${range('Strength','strength',brush.strength,.005,1,.005)}${range('Spacing','spacing',brush.spacing,.01,1,.01)}<div class="f-field"><label>Falloff</label><select id="f-fall"><option ${brush.falloff==='Smooth'?'selected':''}>Smooth</option><option ${brush.falloff==='Linear'?'selected':''}>Linear</option><option ${brush.falloff==='Sharp'?'selected':''}>Sharp</option></select></div><div class="f-label">Symmetry</div><div class="f-checks"><label class="f-check"><input type="checkbox" id="f-sx" ${brush.symX?'checked':''}> X</label><label class="f-check"><input type="checkbox" id="f-sy" ${brush.symY?'checked':''}> Y</label><label class="f-check"><input type="checkbox" id="f-sz" ${brush.symZ?'checked':''}> Z</label></div><div class="f-divider"></div><div class="f-field"><label>Preset Name</label><input id="f-preset-name" value="My Brush"></div><button type="button" class="f-btn f-primary" id="f-save-preset">Save Custom Brush</button><div class="f-divider"></div><div class="f-help">Draw/Clay build surface. Inflate expands along normals. Smooth relaxes topology. Flatten and Scrape plane the surface. Pinch pulls vertices toward the stroke center. Crease combines pinch with an inward cut. Grab drags nearby geometry.</div>`;left.querySelectorAll('[data-brush]').forEach(b=>b.addEventListener('click',()=>{brush.type=b.dataset.brush;renderSculpt()}));bindValues(brush);right.querySelector('#f-fall').addEventListener('change',e=>brush.falloff=e.target.value);['x','y','z'].forEach(a=>right.querySelector('#f-s'+a).addEventListener('change',e=>brush['sym'+a.toUpperCase()]=e.target.checked));right.querySelector('#f-save-preset').addEventListener('click',()=>{const name=right.querySelector('#f-preset-name').value.trim().slice(0,24)||'Custom Brush';presets.push({name,...JSON.parse(JSON.stringify(brush))});renderSculpt()});const ph=left.querySelector('#f-presets');presets.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='f-chip';b.textContent=p.name;b.addEventListener('click',()=>{const {name,...settings}=p;Object.assign(brush,settings);renderSculpt()});ph.appendChild(b)})}
function renderNodes(){const names={source:'Source',transform:'Transform',material:'Material',output:'Output',twist:'Twist',bend:'Bend',taper:'Taper',noise:'Noise',spherize:'Spherize',flatten:'Flatten'};left.innerHTML=`<div class="f-label">Add Modifier Node</div>${btns([['twist','Twist'],['bend','Bend'],['taper','Taper'],['noise','Noise'],['spherize','Spherize'],['flatten','Flatten']])}<div class="f-divider"></div><div class="f-node-list" id="f-node-list"></div>`;const list=left.querySelector('#f-node-list');nodes.forEach((n,i)=>{const e=document.createElement('div');e.className=`f-node ${n.type} ${n.id===nodeSelected?'selected':''} ${n.enabled?'':'off'}`;e.innerHTML=`<div class="f-node-title"><span class="f-dot"></span>${names[n.type]}</div><div class="f-node-sub">${n.type==='source'?(n.p.custom?'Custom mesh':n.p.shape):n.type==='output'?'Final geometry':n.enabled?'Enabled':'Disabled'}</div>${!['source','output'].includes(n.type)?`<div class="f-node-actions"><button type="button" class="f-mini" data-a="toggle">${n.enabled?'Disable':'Enable'}</button>${deformation.has(n.type)?'<button type="button" class="f-mini" data-a="up">↑</button><button type="button" class="f-mini" data-a="down">↓</button><button type="button" class="f-mini" data-a="delete">Delete</button>':''}</div>`:''}`;e.addEventListener('click',ev=>{const a=ev.target.closest('button')?.dataset.a;if(a){ev.stopPropagation();nodeAction(n,a);return}nodeSelected=n.id;renderNodes()});list.appendChild(e)});left.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.tool,n={id:'n'+idN++,type,enabled:true,p:JSON.parse(JSON.stringify(D[type]))};const at=nodes.findIndex(x=>x.type==='transform');nodes.splice(at,0,n);nodeSelected=n.id;evaluate();pushHistory();renderNodes()}));renderNodeInspector()}
function nodeAction(n,a){if(a==='toggle')n.enabled=!n.enabled;else if(a==='delete')nodes.splice(nodes.indexOf(n),1);else{const i=nodes.indexOf(n),j=a==='up'?i-1:i+1;if(j>0&&j<nodes.length&&deformation.has(nodes[j]?.type))[nodes[i],nodes[j]]=[nodes[j],nodes[i]]}evaluate();pushHistory();renderNodes()}
function renderNodeInspector(){const n=nodes.find(x=>x.id===nodeSelected);if(!n){right.innerHTML='<div class="f-help">Select a node.</div>';return}if(n.type==='source'){const s=n.p;right.innerHTML=`<div class="f-field"><label>Primitive</label><select id="f-shape"><option>Box</option><option>Sphere</option><option>Cylinder</option><option>Torus</option></select></div>${num('X Size','sizeX',s.sizeX,.05,50)}${num('Y Size','sizeY',s.sizeY,.05,50)}${num('Z Size','sizeZ',s.sizeZ,.05,50)}${num('Radius','radius',s.radius,.05,30)}${num('Height','height',s.height,.05,50)}${num('Segments','segments',s.segments,4,64,1)}<div class="f-help">Changing a source parameter rebuilds the primitive and replaces manual/sculpt changes.</div>`;const sh=right.querySelector('#f-shape');sh.value=s.shape==='Custom'?'Box':s.shape;sh.addEventListener('change',()=>makeSource(sh.value));bindValues(s,()=>makeSource(sh.value));return}if(n.type==='transform'||n.type==='material'){right.innerHTML='<div class="f-help">Use Object mode for transform and material properties. These are still represented as nodes in the stack.</div>';return}if(n.type==='output'){right.innerHTML='<div class="f-help">Output displays the final evaluated geometry after all enabled nodes.</div>';return}let h='';if(n.type==='twist'||n.type==='bend')h+=num('Angle °','amount',n.p.amount,-1440,1440,1);if(n.type==='taper')h+=num('Factor','factor',n.p.factor,-3,5,.05);if(n.type==='noise')h+=range('Strength','strength',n.p.strength,0,3,.01)+range('Frequency','frequency',n.p.frequency,.05,20,.05)+num('Seed','seed',n.p.seed,0,9999,1);if(n.type==='spherize')h+=range('Factor','factor',n.p.factor,0,1,.01);if(n.type==='flatten')h+=num('Plane','amount',n.p.amount,-20,20,.05);if(['twist','bend','taper','flatten'].includes(n.type))h+=`<div class="f-field"><label>Axis</label><select id="f-axis"><option value="x">X</option><option value="y">Y</option><option value="z">Z</option></select></div>`;h+=`<div class="f-divider"></div><button type="button" class="f-btn" id="f-bake-one">Bake All Modifier Nodes</button>`;right.innerHTML=h;bindValues(n.p,()=>evaluate());const ax=right.querySelector('#f-axis');if(ax){ax.value=n.p.axis;ax.addEventListener('change',()=>{n.p.axis=ax.value;evaluate();pushHistory()})}right.querySelector('#f-bake-one').addEventListener('click',()=>{bakeModifiers();renderNodes()})}
function updateFaceMark(){if(faceMark){mesh?.remove(faceMark);faceMark.geometry.dispose();faceMark.material.dispose();faceMark=null}if(workspace!=='edit'||selectedFace<0||!mesh)return;const f=faceIndices(mesh.geometry,selectedFace);if(!f)return;const p=mesh.geometry.attributes.position,a=new THREE.Vector3().fromBufferAttribute(p,f[0]),b=new THREE.Vector3().fromBufferAttribute(p,f[1]),c=new THREE.Vector3().fromBufferAttribute(p,f[2]),n=b.clone().sub(a).cross(c.clone().sub(a)).normalize().multiplyScalar(.004),arr=[a.x+n.x,a.y+n.y,a.z+n.z,b.x+n.x,b.y+n.y,b.z+n.z,c.x+n.x,c.y+n.y,c.z+n.z];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));faceMark=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0xffcc00,transparent:true,opacity:.48,side:THREE.DoubleSide,depthTest:false}));mesh.add(faceMark)}
const ray=new THREE.Raycaster(),ndc=new THREE.Vector2();
function rayHit(e){const r=renderer.domElement.getBoundingClientRect();ndc.x=((e.clientX-r.left)/r.width)*2-1;ndc.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(ndc,camera);return ray.intersectObject(mesh,false)[0]||null}
function localPoint(world){return mesh.worldToLocal(world.clone())}
function localNormal(hit){const n=hit.face.normal.clone();const normalMatrix=new THREE.Matrix3().getNormalMatrix(mesh.matrixWorld);const wn=n.applyMatrix3(normalMatrix).normalize();const inv=new THREE.Matrix3().getNormalMatrix(mesh.matrixWorld.clone().invert());return wn.applyMatrix3(inv).normalize()}
function symmetryCenters(c,n){let out=[{c:c.clone(),n:n.clone()}];for(const ax of ['X','Y','Z'])if(brush['sym'+ax]){const a=ax.toLowerCase(),copy=out.map(q=>{const cc=q.c.clone(),nn=q.n.clone();cc[a]*=-1;nn[a]*=-1;return{c:cc,n:nn}});out=out.concat(copy)}return out}
function falloff(t){t=Math.max(0,Math.min(1,t));if(brush.falloff==='Sharp')return t*t*t*t;if(brush.falloff==='Linear')return t;return t*t*(3-2*t)}
function refreshSculpt(){baseGeometry.computeVertexNormals();const bp=baseGeometry.attributes.position,mp=mesh.geometry.attributes.position;if(mp.count===bp.count){mp.array.set(bp.array);mp.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingSphere()}else evaluate();updateStatus()}
function sculptStroke(hit,e){if(!hit)return;const center=localPoint(hit.point),normal=localNormal(hit),pos=baseGeometry.attributes.position,nor=baseGeometry.attributes.normal;if(!adjacency)adjacency=adjacencyFor(baseGeometry);const centers=symmetryCenters(center,normal),old=Array.from(pos.array),v=new THREE.Vector3(),tmp=new THREE.Vector3();const dx=lastPointer?e.clientX-lastPointer.x:0,dy=lastPointer?e.clientY-lastPointer.y:0;const camRight=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),camUp=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1),dragWorld=camRight.multiplyScalar(dx*.0025*brush.radius).add(camUp.multiplyScalar(-dy*.0025*brush.radius));const dragLocal=dragWorld.clone().applyQuaternion(mesh.getWorldQuaternion(new THREE.Quaternion()).invert());for(const cn of centers){for(let i=0;i<pos.count;i++){v.fromBufferAttribute(pos,i);const d=v.distanceTo(cn.c);if(d>brush.radius)continue;const w=falloff(1-d/brush.radius)*brush.strength;if(w<=0)continue;if(brush.type==='Smooth'){const nei=adjacency[i];if(nei?.size){tmp.set(0,0,0);for(const j of nei)tmp.add(new THREE.Vector3(old[j*3],old[j*3+1],old[j*3+2]));tmp.multiplyScalar(1/nei.size);v.lerp(tmp,Math.min(1,w*2.5))}}else if(brush.type==='Flatten'||brush.type==='Scrape'){const dist=v.clone().sub(cn.c).dot(cn.n);if(brush.type==='Flatten'||dist>0)v.addScaledVector(cn.n,-dist*Math.min(1,w*2.2))}else if(brush.type==='Pinch'){tmp.copy(cn.c).sub(v);tmp.addScaledVector(cn.n,-tmp.dot(cn.n));v.addScaledVector(tmp,w*1.6)}else if(brush.type==='Crease'){tmp.copy(cn.c).sub(v);tmp.addScaledVector(cn.n,-tmp.dot(cn.n));v.addScaledVector(tmp,w*1.25).addScaledVector(cn.n,-w*.16)}else if(brush.type==='Grab')v.addScaledVector(dragLocal,w*6);else{const nv=new THREE.Vector3(nor.getX(i),nor.getY(i),nor.getZ(i));const mult=brush.type==='Inflate'?1.5:brush.type==='Clay'?.85:1;v.addScaledVector(nv,w*mult)}pos.setXYZ(i,v.x,v.y,v.z)}}pos.needsUpdate=true;refreshSculpt();strokeDirty=true;lastPointer={x:e.clientX,y:e.clientY};lastBrushPoint=center}
function updateBrushCursor(hit){if(!brushCursor)return;if(workspace!=='sculpt'||!hit){brushCursor.visible=false;return}brushCursor.visible=true;brushCursor.position.copy(hit.point);brushCursor.scale.setScalar(brush.radius);const normal=hit.face.normal.clone().transformDirection(mesh.matrixWorld);brushCursor.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal.normalize())}
function frame(){if(!mesh)return;mesh.geometry.computeBoundingSphere();const r=Math.max(1,mesh.geometry.boundingSphere.radius*Math.max(mesh.scale.x,mesh.scale.y,mesh.scale.z));orbit.target.copy(mesh.position);camera.position.set(mesh.position.x+r*3.1,mesh.position.y+r*2.3,mesh.position.z+r*3.2);orbit.update()}
try{
 const mods=await Promise.all([
 import('https://cdn.jsdelivr.net/npm/three@0.185.0/+esm'),
 import('https://cdn.jsdelivr.net/npm/three@0.185.0/examples/jsm/controls/OrbitControls.js/+esm'),
 import('https://cdn.jsdelivr.net/npm/three@0.185.0/examples/jsm/controls/TransformControls.js/+esm'),
 import('https://cdn.jsdelivr.net/npm/three@0.185.0/examples/jsm/utils/BufferGeometryUtils.js/+esm')
]);THREE=mods[0];OrbitControls=mods[1].OrbitControls;TransformControls=mods[2].TransformControls;mergeVertices=mods[3].mergeVertices;
 scene=new THREE.Scene();scene.background=new THREE.Color(0x13161b);camera=new THREE.PerspectiveCamera(48,1,.04,600);camera.position.set(6,5,7);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;view.insertBefore(renderer.domElement,view.firstChild);scene.add(new THREE.HemisphereLight(0xffffff,0x303844,2.2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(6,9,6);key.castShadow=true;scene.add(key);scene.add(new THREE.GridHelper(30,30,0x69727d,0x333941));scene.add(new THREE.AxesHelper(3));const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.ShadowMaterial({opacity:.17}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
 orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.07;orbit.target.set(0,1,0);orbit.touches.ONE=THREE.TOUCH.ROTATE;orbit.touches.TWO=THREE.TOUCH.DOLLY_PAN;gizmo=new TransformControls(camera,renderer.domElement);gizmoHelper=gizmo.getHelper?gizmo.getHelper():gizmo;scene.add(gizmoHelper);gizmo.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);gizmo.addEventListener('objectChange',()=>{const t=transformNode().p;t.px=+mesh.position.x.toFixed(3);t.py=+mesh.position.y.toFixed(3);t.pz=+mesh.position.z.toFixed(3);t.rx=+THREE.MathUtils.radToDeg(mesh.rotation.x).toFixed(2);t.ry=+THREE.MathUtils.radToDeg(mesh.rotation.y).toFixed(2);t.rz=+THREE.MathUtils.radToDeg(mesh.rotation.z).toFixed(2);t.sx=+mesh.scale.x.toFixed(3);t.sy=+mesh.scale.y.toFixed(3);t.sz=+mesh.scale.z.toFixed(3)});gizmo.addEventListener('mouseUp',()=>{pushHistory();if(workspace==='object')renderObject()});
 brushCursor=new THREE.Mesh(new THREE.RingGeometry(.94,1,64),new THREE.MeshBasicMaterial({color:0xffcc00,transparent:true,opacity:.85,side:THREE.DoubleSide,depthTest:false}));brushCursor.visible=false;scene.add(brushCursor);
 baseGeometry=mergeVertices(new THREE.BoxGeometry(2,2,2,5,5,5).toNonIndexed(),1e-5);baseGeometry.computeVertexNormals();evaluate();pushHistory();renderWorkspace();frame();
 const resize=()=>{const w=Math.max(1,view.clientWidth),h=Math.max(1,view.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};new ResizeObserver(resize).observe(view);resize();const animate=()=>{requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera)};animate();
 renderer.domElement.addEventListener('pointerdown',e=>{lastPointer={x:e.clientX,y:e.clientY};if(workspace==='sculpt'){bakeModifiers();adjacency=adjacencyFor(baseGeometry);const h=rayHit(e);if(h){sculpting=true;orbit.enabled=false;renderer.domElement.setPointerCapture?.(e.pointerId);sculptStroke(h,e)}}});renderer.domElement.addEventListener('pointermove',e=>{const h=rayHit(e);updateBrushCursor(h);if(workspace==='sculpt'&&sculpting){if(lastPointer){const d=Math.hypot(e.clientX-lastPointer.x,e.clientY-lastPointer.y);if(d<brush.spacing*20)return}sculptStroke(h,e)}});renderer.domElement.addEventListener('pointerup',e=>{if(workspace==='edit'&&lastPointer&&Math.hypot(e.clientX-lastPointer.x,e.clientY-lastPointer.y)<7){const h=rayHit(e);if(h){selectedFace=h.faceIndex;updateFaceMark();renderEdit()}}if(workspace==='sculpt'&&sculpting){sculpting=false;orbit.enabled=true;adjacency=null;if(strokeDirty){sourceNode().p.custom=true;sourceNode().p.shape='Custom';pushHistory();strokeDirty=false}}lastPointer=null});renderer.domElement.addEventListener('pointerleave',()=>{if(!sculpting)brushCursor.visible=false});
}catch(err){console.error(err);status.textContent='Three.js modeling engine could not load. Check your internet connection and reload.'}
R.querySelectorAll('[data-work]').forEach(b=>b.addEventListener('click',()=>setWorkspace(b.dataset.work)));R.querySelectorAll('[data-gizmo]').forEach(b=>b.addEventListener('click',()=>{gizmoMode=b.dataset.gizmo;gizmo.setMode(gizmoMode);R.querySelectorAll('[data-gizmo]').forEach(x=>x.classList.toggle('active',x===b))}));R.querySelector('#f-space').addEventListener('click',e=>{space=space==='world'?'local':'world';gizmo.setSpace(space);e.currentTarget.textContent=space[0].toUpperCase()+space.slice(1)});R.querySelector('#f-frame').addEventListener('click',frame);R.querySelector('#f-wire').addEventListener('click',e=>{wire=!wire;e.currentTarget.classList.toggle('active',wire);evaluate()});R.querySelector('#f-undo').addEventListener('click',()=>restore(hist-1));R.querySelector('#f-redo').addEventListener('click',()=>restore(hist+1));